### ISSUE TITLE
Send Kyma CR object key in the watcher payload to identify which SKR the watched resource belongs to  

### ISSUE THREAD

**Issue by fourthisle** [kyma-project/runtime-watcher#100]
**Description:**

In the current watcher-listener payload, it is not possible to know which SKR the watched resource belongs to. The payload should be extended to include this information as it enables KCP components other than lifecycle-manager which have use cases to watch SKR resources.  

**AC:**

- [ ] Extend the watcher-listener payload to include the Kyma CR name and namespace.
Example:
```
type WatchEvent struct {
        Kyma       client.ObjectKey        `json:"kyma"`
	Owner      client.ObjectKey        `json:"owner"`
	Watched    client.ObjectKey        `json:"watched"`
	WatchedGvk metav1.GroupVersionKind `json:"watchedGvk"`
}
```
- [ ] Implement additional logic that resolves the SKR Kyma CR when sending the payload to the listener.

**Comment by khlifi411** [comment]
After further investigation, it turns out that this change request is not required. While installing the resource to be watched, the central-component (component deployed on KCP) needs to apply an `owned-by` annotation with the `namespace/name` combination of which Kyma CR (or any tuple identifier it may choose) to the to-be-watched resource. The watcher will send that back in the `owner` field in the KCP payload sent to the listener endpoint.
The following is a sample secret resource that contains the `owned-by` annotation referencing the SKR, which corresponds to the Kyma CR `kyma-sample` belonging to the `kcp-system` namespace:
```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: keb-secret
  namespace: kcp-system
  labels:
    "operator.kyma-project.io/watched-by": "lifecycle-manager"
    "operator.kyma-project.io/managed-by": "lifecycle-manager"
  annotations:
    "operator.kyma-project.io/owned-by": "kcp-system/kyma-sample"
data:
  config: Y29uZmln
  cfg: Y2Zn
```
